version: '3.4'

services:
  catalog.db:
    image: mongo:latest
    
  basket.db:
    image: redis:alpine
    
  discount.db:
    image: postgres:alpine
    
  pgadmin:
    image: dpage/pgadmin4
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
        
volumes:
  mongo_data:
  postgres_data:
  pgadmin_data: